version: "2"
services:
    server:
        build: .
        command: bash -c "./_result/server"
        #command: bash -c "pwd && cd _result/"
        ports:
            - 3990:3990
        volumes:
            - .:/usr/src/poke_bat
        networks:
            - poke_net
    database:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '1'
            MYSQL_DATABASE: 'poke_bat'
            #MYSQL_USER: 'test'
            #MYSQL_PASS: 'pass'
        depends_on:
            - server
        networks:
            - poke_net

networks:
    poke_net:
        driver: bridge
