version: "3"
services:
    pokebat_db:
        image: mysql:5.7
        restart: always
        volumes:
            - "./tmp_docker_pokebat_mysql:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=eGSiwphc8E
            - MYSQL_USER=pokebatuser
            - MYSQL_PASSWORD=pokebatpass
            - MYSQL_DATABASE=pokebatdb
        networks:
            - pokebat_net

    pokebat_server:
        image: sibirctf2019/poke_bat_server:0.0.2
        depends_on:
            - pokebat_db
        restart: always
        volumes:
            - "./pokebat_dist.conf:/etc/pokebat.conf"
        ports:
            - 3990:3990
        networks:
            - pokebat_net

networks:
    pokebat_net:
        driver: bridge
