/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "interfaces_constants.h"



const interfacesConstants g_interfaces_constants;

interfacesConstants::interfacesConstants() {
}



