/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef interfaces_CONSTANTS_H
#define interfaces_CONSTANTS_H

#include "interfaces_types.h"



class interfacesConstants {
 public:
  interfacesConstants();

};

extern const interfacesConstants g_interfaces_constants;



#endif
