version: '3'

services:
  team1_service2_pokebat_db:
    image: mysql:5.7
    restart: always
    volumes:
      - "./tmp_docker_team1_service2_mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=nIsWqicYNB
      - MYSQL_USER=pokebatuser
      - MYSQL_PASSWORD=pokebatpass
      - MYSQL_DATABASE=pokebatdb
    networks:
      - fhqjuryad_net

  team1_service2_pokebat_server:
    image: sibirctf2019/poke_bat_server:0.0.2
    depends_on:
      - team1_service2_pokebat_db
    restart: always
    ports:
      - 3990:3990
    volumes:
      - "./team1_poketbat.conf:/etc/pokebat.conf"
    networks:
      - fhqjuryad_net

  team2_service2_pokebat_db:
    image: mysql:5.7
    restart: always
    volumes:
      - "./tmp_docker_team2_service2_mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=aCPHKfcGHX
      - MYSQL_USER=pokebatuser2
      - MYSQL_PASSWORD=pokebatpass2
      - MYSQL_DATABASE=pokebatdb2
    networks:
      - fhqjuryad_net

  team2_service2_pokebat_server:
    image: sibirctf2019/poke_bat_server:0.0.2
    depends_on:
      - team2_service2_pokebat_db
    restart: always
    ports:
      - 3991:3990
    volumes:
      - "./team2_poketbat.conf:/etc/pokebat.conf"
    networks:
      - fhqjuryad_net

  fhqjuryad_db:
    image: mysql:5.7
    volumes:
      - "./tmp_docker_jury_mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KzhyntJxwt
      MYSQL_DATABASE: fhqjuryad
      MYSQL_USER: fhqjuryad
      MYSQL_PASSWORD: fhqjuryad
    networks:
      - fhqjuryad_net

  fhqjuryad_jury:
    depends_on:
      - fhqjuryad_db
    build: ./
    image: fhqjuryad_jury_for_pokebat
    volumes:
      - "./jury.d:/usr/share/fhq-jury-ad/jury.d"
    ports:
      - "7111:7111"
    restart: always
    links:
      - "fhqjuryad_db"
    networks:
      - fhqjuryad_net

networks:
  fhqjuryad_net:
    driver: bridge
