// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/PokServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include "pok_server.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::poke_bat::middleware;



PokServerHandler::PokServerHandler()
{
    // Your initialization goes here
}

void PokServerHandler::getConfig(Config& _return)
{
  // Your implementation goes here
  printf("getConfig\n");
}

void PokServerHandler::startFight(Pokemon& _return, const int64_t complexity, const Pokemon& clientPokemon)
{
  // Your implementation goes here
  printf("startFight\n");
}

void PokServerHandler::punch(RoundResult& _return)
{
  // Your implementation goes here
  printf("punch\n");
}

void PokServerHandler::defend(RoundResult& _return)
{
  // Your implementation goes here
  printf("defend\n");
}

void PokServerHandler::useSkill(RoundResult& _return, const std::string& skillName)
{
  // Your implementation goes here
  printf("useSkill\n");
}
